# Generated by Django 5.1.6 on 2025-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_quotation_order_number_quotation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
