# Generated by Django 5.1.6 on 2025-02-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_remove_product_built_in_interface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
