# Generated by Django 5.1.6 on 2025-02-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_quotation_delivery_address_quotation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
    ]
